name: Linting

on: [push, pull_request]

jobs:
  linting:
    name: Linting (.js/.ts/.html/.scss)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
      - run: npm install --save-dev @angular/cli
      - run: npm install
      - name: eslint (.js/.ts/.html)
        run: npm run lint:eslint -- --max-warnings=0
      - name: stylelint (.scss)
        run: npm run lint:stylelint
