name: Linting

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
      - run: npm install -g @angular/cli
      - run: npm install
      - run: npm run lint -- --max-warnings=0